// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NorusProject.Models;

namespace NorusProject.Migrations
{
    [DbContext(typeof(NorusProjectContext))]
    [Migration("20190716171739_CreateStruct")]
    partial class CreateStruct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NorusProject.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("NorusProject.Models.Contratos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientesId");

                    b.Property<string>("TipoContrato");

                    b.Property<decimal?>("QtdNegociada");
					
					b.Property<decimal?>("VlrNegociado");
					
					b.Property<string>("MesAnoInicioContrato");
					
					b.Property<string>("DuracaoMesesContrato");

                    b.HasKey("Id");

                    b.HasIndex("ClientesId");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("NorusProject.Models.Contratos", b =>
                {
                    b.HasOne("NorusProject.Models.Clientes", "Clientes")
                        .WithMany("Contratos")
                        .HasForeignKey("ClientesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
