// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NorusProject.Models;

namespace NorusProject.Migrations
{
    [DbContext(typeof(NorusProjectContext))]
    [Migration("20200618192603_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NorusProject.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("NorusProject.Models.Contratos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientesId");

                    b.Property<string>("DuracaoMesesContrato")
                        .IsRequired();

                    b.Property<string>("MesAnoInicioContrato")
                        .IsRequired();

                    b.Property<decimal?>("QtdNegociada")
                        .IsRequired();

                    b.Property<string>("TipoContrato")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<decimal?>("VlrNegociado")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ClientesId");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("NorusProject.Models.Contratos", b =>
                {
                    b.HasOne("NorusProject.Models.Clientes", "Clientes")
                        .WithMany("Contratos")
                        .HasForeignKey("ClientesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
